mp.openapi.extensions.smallrye.info.title=Book API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=Creates Books
mp.openapi.extensions.smallrye.info.contact.name=@Ahnaf
mp.openapi.extensions.smallrye.info.contact.email=ahnaf.tahmid0628@gmail.com


quarkus.http.port=8702
quarkus.console.color=true

quarkus.rest-client."org.agoncal.quarkus.microservices.number.NumberProxy".url=http://localhost:8701